services:
  - type: web
    name: vscode-stimulator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gthread --threads 8 -w 1 backend.app:app --bind 0.0.0.0:$PORT --timeout 180
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WORKSPACE_ROOT
        value: /opt/render/project/src/workspace
